export const mockOrders = [
    {
    orderId: 997,
    brand: 'WebContent',
    cvr: '40791752',
    contact: {
        name: 'Mathias Hansen',
        phone: '12344321',
        email: 'info@webcontent.dk',
    },
    projectName: 'UGC kampagne',
    projectType: 'User Generated Content',
    contentCount: 5,
    contentLength: 60,
    channels: 'TikTok, Instagram',
    format: '9:16, 4:5',
    extraCreator: true,
    extraHook: true,
    extraHookCount: 2,
    extraNotes: 'Vægt på reviews og testimonials',
    notes: 'Reklamefilm til WebContents nye digitale alt-i-en platform',
    isConfirmed: true,
    source: 'LinkedIn',
    price: 6219,
    status: 1,
    deliveryTimeFrom: 1,
    deliveryTimeTo: 3,
    isDenied: false,
    isComplete: false,
    },
    {
    orderId: 998,
    brand: 'WebContent',
    cvr: '40791752',
    contact: {
        name: 'Mathias Hansen',
        phone: '12344321',
        email: 'info@webcontent.dk',
    },
    projectName: 'Content Cloud',
    projectType: 'User Generated Content',
    contentCount: 5,
    contentLength: 60,
    channels: 'TikTok, Instagram',
    format: '9:16, 4:5',
    extraCreator: true,
    extraHook: true,
    extraHookCount: 2,
    extraNotes: 'Vægt på reviews og testimonials',
    notes: 'Reklamefilm til WebContents nye digitale alt-i-en platform',
    isConfirmed: false,
    source: 'LinkedIn',
    price: 6219,
    deliveryTimeFrom: 1,
    deliveryTimeTo: 3,
    isDenied: false,
    isComplete: false,
    },
    {
    orderId: 999,
    brand: 'WebContent',
    cvr: '40791752',
    contact: {
        name: 'Mathias Hansen',
        phone: '12344321',
        email: 'info@webcontent.dk',
    },
    projectName: 'Produkt Reklamefilm',
    projectType: 'User Generated Content',
    contentCount: 5,
    contentLength: 60,
    channels: 'TikTok, Instagram',
    format: '9:16, 4:5',
    extraCreator: true,
    extraHook: true,
    extraHookCount: 2,
    extraNotes: 'Vægt på reviews og testimonials',
    notes: 'Reklamefilm til WebContents nye digitale alt-i-en platform',
    isConfirmed: true,
    status: 1,
    source: 'LinkedIn',
    price: 6219,
    deliveryTimeFrom: 1,
    deliveryTimeTo: 3,
    isDenied: false,
    isComplete: false,
    },
]